import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import Navbar from "@/components/view/Navbar";
import Providers from "@/providers";
import { Toaster } from "@/components/ui/sonner";
import Hero from "@/components/home/hero/Hero";
import About from "@/components/home/about/About";
import FeaturedProducts from "@/components/home/featured-products/FeaturedProducts";
import Values from "@/components/home/values/Values";
import Gallery from "@/components/home/gallery/Gallery";
import Testimonials from "@/components/home/testimonials/Testimonials";
import Cta from "@/components/home/cta/Cta";
import Layout from "@/components/layout/Index";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
        >
          <Toaster />

          <Layout>{children}</Layout>
        </body>
      </Providers>
    </html>
  );
}
